//! The standard condition class hierarchy table (C4).

/// One standard condition class and its direct superclasses.
pub struct HierarchyRow {
    /// Class name.
    pub name: &'static str,
    /// Direct superclass names, in most-specific-first order. Empty for the
    /// root `condition`. More than one entry models genuine ANSI multiple
    /// inheritance (for example `simple-error` under both `simple-condition`
    /// and `error`).
    // check-added-lines: allow(index) slice type, not indexing
    pub superclasses: &'static [&'static str],
}
/// The standard condition hierarchy. Most rows single-inherit, but a handful
/// of ANSI-mandated "simple-*" types have two direct superclasses.
#[rustfmt::skip]
pub const HIERARCHY: &[HierarchyRow] = &[
    HierarchyRow { name: "CONDITION", superclasses: &[] },
    HierarchyRow { name: "WARNING", superclasses: &["CONDITION"] },
    HierarchyRow { name: "SERIOUS-CONDITION", superclasses: &["CONDITION"] },
    HierarchyRow { name: "ERROR", superclasses: &["SERIOUS-CONDITION"] },
    HierarchyRow { name: "STORAGE-CONDITION", superclasses: &["SERIOUS-CONDITION"] },
    HierarchyRow { name: "TYPE-ERROR", superclasses: &["ERROR"] },
    HierarchyRow { name: "ARITHMETIC-ERROR", superclasses: &["ERROR"] },
    HierarchyRow { name: "DIVISION-BY-ZERO", superclasses: &["ARITHMETIC-ERROR"] },
    HierarchyRow { name: "FLOATING-POINT-OVERFLOW", superclasses: &["ARITHMETIC-ERROR"] },
    HierarchyRow { name: "FLOATING-POINT-UNDERFLOW", superclasses: &["ARITHMETIC-ERROR"] },
    HierarchyRow { name: "FLOATING-POINT-INVALID-OPERATION", superclasses: &["ARITHMETIC-ERROR"] },
    HierarchyRow { name: "FLOATING-POINT-INEXACT", superclasses: &["ARITHMETIC-ERROR"] },
    HierarchyRow { name: "CELL-ERROR", superclasses: &["ERROR"] },
    HierarchyRow { name: "UNBOUND-VARIABLE", superclasses: &["CELL-ERROR"] },
    HierarchyRow { name: "UNDEFINED-FUNCTION", superclasses: &["CELL-ERROR"] },
    HierarchyRow { name: "UNBOUND-SLOT", superclasses: &["CELL-ERROR"] },
    HierarchyRow { name: "FILE-ERROR", superclasses: &["ERROR"] },
    HierarchyRow { name: "PACKAGE-ERROR", superclasses: &["ERROR"] },
    HierarchyRow { name: "CONTROL-ERROR", superclasses: &["ERROR"] },
    HierarchyRow { name: "PROGRAM-ERROR", superclasses: &["ERROR"] },
    HierarchyRow { name: "PARSE-ERROR", superclasses: &["ERROR"] },
    HierarchyRow { name: "READER-ERROR", superclasses: &["PARSE-ERROR", "STREAM-ERROR"] },
    HierarchyRow { name: "PRINT-NOT-READABLE", superclasses: &["ERROR"] },
    HierarchyRow { name: "STREAM-ERROR", superclasses: &["ERROR"] },
    HierarchyRow { name: "END-OF-FILE", superclasses: &["STREAM-ERROR"] },
    HierarchyRow { name: "SIMPLE-CONDITION", superclasses: &["CONDITION"] },
    HierarchyRow { name: "SIMPLE-ERROR", superclasses: &["SIMPLE-CONDITION", "ERROR"] },
    HierarchyRow { name: "SIMPLE-TYPE-ERROR", superclasses: &["SIMPLE-CONDITION", "TYPE-ERROR"] },
    HierarchyRow { name: "SIMPLE-WARNING", superclasses: &["SIMPLE-CONDITION", "WARNING"] },
    HierarchyRow { name: "STYLE-WARNING", superclasses: &["WARNING"] },
    HierarchyRow { name: "UNDEFINED-ALIEN-ERROR", superclasses: &["ERROR"] },
    HierarchyRow { name: "CODE-DELETION-NOTE", superclasses: &["CONDITION"] },
    HierarchyRow { name: "COMPILER-NOTE", superclasses: &["CONDITION"] },
    HierarchyRow { name: "DEFCONSTANT-UNEQL", superclasses: &["ERROR"] },
    HierarchyRow { name: "DELETE-FILE-ERROR", superclasses: &["FILE-ERROR"] },
    HierarchyRow { name: "DEPRECATION-CONDITION", superclasses: &["CONDITION"] },
    HierarchyRow { name: "DEPRECATION-ERROR", superclasses: &["DEPRECATION-CONDITION"] },
    HierarchyRow { name: "EARLY-DEPRECATION-WARNING", superclasses: &["STYLE-WARNING"] },
    HierarchyRow { name: "FILE-DOES-NOT-EXIST", superclasses: &["FILE-ERROR"] },
    HierarchyRow { name: "FILE-EXISTS", superclasses: &["FILE-ERROR"] },
    HierarchyRow { name: "FINAL-DEPRECATION-WARNING", superclasses: &["STYLE-WARNING"] },
    HierarchyRow { name: "IMPLICIT-GENERIC-FUNCTION-WARNING", superclasses: &["STYLE-WARNING"] },
    HierarchyRow { name: "INVALID-FASL", superclasses: &["ERROR"] },
    HierarchyRow { name: "LATE-DEPRECATION-WARNING", superclasses: &["STYLE-WARNING"] },
    HierarchyRow { name: "NAME-CONFLICT", superclasses: &["ERROR"] },
    HierarchyRow { name: "PACKAGE-DOES-NOT-EXIST", superclasses: &["ERROR"] },
    HierarchyRow { name: "PACKAGE-LOCK-VIOLATION", superclasses: &["ERROR"] },
    HierarchyRow { name: "PACKAGE-LOCKED-ERROR", superclasses: &["PACKAGE-ERROR"] },
    HierarchyRow { name: "READER-PACKAGE-DOES-NOT-EXIST", superclasses: &["ERROR"] },
    HierarchyRow { name: "STEP-CONDITION", superclasses: &["CONDITION"] },
    HierarchyRow { name: "STEP-FINISHED-CONDITION", superclasses: &["STEP-CONDITION"] },
    HierarchyRow { name: "STEP-FORM-CONDITION", superclasses: &["STEP-CONDITION"] },
    HierarchyRow { name: "STEP-VALUES-CONDITION", superclasses: &["STEP-CONDITION"] },
    HierarchyRow { name: "SYMBOL-PACKAGE-LOCKED-ERROR", superclasses: &["PACKAGE-LOCKED-ERROR"] },
    HierarchyRow { name: "TIMEOUT", superclasses: &["ERROR"] },
    HierarchyRow { name: "UNKNOWN-KEYWORD-ARGUMENT", superclasses: &["ERROR"] },
    HierarchyRow { name: "SYSTEM-CONDITION", superclasses: &["CONDITION"] },
    HierarchyRow { name: "BREAKPOINT-ERROR", superclasses: &["ERROR"] },
    HierarchyRow { name: "DEADLINE-TIMEOUT", superclasses: &["TIMEOUT"] },
    HierarchyRow { name: "INTERACTIVE-INTERRUPT", superclasses: &["SYSTEM-CONDITION"] },
    HierarchyRow { name: "IO-TIMEOUT", superclasses: &["TIMEOUT"] },
    HierarchyRow { name: "MEMORY-FAULT-ERROR", superclasses: &["STORAGE-CONDITION"] },
    HierarchyRow { name: "THREAD-ERROR", superclasses: &["ERROR"] },
    HierarchyRow { name: "INTERRUPT-THREAD-ERROR", superclasses: &["THREAD-ERROR"] },
    HierarchyRow { name: "JOIN-THREAD-ERROR", superclasses: &["THREAD-ERROR"] },
    HierarchyRow { name: "SYMBOL-VALUE-IN-THREAD-ERROR", superclasses: &["THREAD-ERROR"] },
    HierarchyRow { name: "THREAD-DEADLOCK", superclasses: &["THREAD-ERROR"] },
];
