[workspace]
resolver = "3"
members = [
    ".",
    "packages/core/syntax",
    "packages/core/compiler",
    "packages/core/runtime",
]
default-members = [
    ".",
    "packages/core/syntax",
    "packages/core/compiler",
    "packages/core/runtime",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
license = "MIT"

[workspace.dependencies]
ncl-syntax = { path = "packages/core/syntax" }
ncl-compiler = { path = "packages/core/compiler" }
ncl-runtime = { path = "packages/core/runtime" }

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
strip = "symbols"

[package]
name = "ncl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

description = "A Rust-native Common Lisp runtime"
license.workspace = true

[lints]
workspace = true

[dependencies]
ncl-runtime.workspace = true
ncl-syntax.workspace = true
