// Generated by tools/gen_unicode.py; do not edit.
// Unicode version: 16.0.0
// Source: https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt
pub const GENERAL_CATEGORY_RANGES: &[&[(u32, u32, &str)]] = &[
    include!("unicode_data/general_category_ranges_00.rs"),
    include!("unicode_data/general_category_ranges_01.rs"),
    include!("unicode_data/general_category_ranges_02.rs"),
    include!("unicode_data/general_category_ranges_03.rs"),
    include!("unicode_data/general_category_ranges_04.rs"),
    include!("unicode_data/general_category_ranges_05.rs"),
    include!("unicode_data/general_category_ranges_06.rs"),
    include!("unicode_data/general_category_ranges_07.rs"),
    include!("unicode_data/general_category_ranges_08.rs"),
];

pub const DECOMPOSITIONS: &[&[(u32, bool, &[u32])]] = &[
    include!("unicode_data/decompositions_00.rs"),
    include!("unicode_data/decompositions_01.rs"),
    include!("unicode_data/decompositions_02.rs"),
    include!("unicode_data/decompositions_03.rs"),
    include!("unicode_data/decompositions_04.rs"),
    include!("unicode_data/decompositions_05.rs"),
    include!("unicode_data/decompositions_06.rs"),
    include!("unicode_data/decompositions_07.rs"),
    include!("unicode_data/decompositions_08.rs"),
    include!("unicode_data/decompositions_09.rs"),
    include!("unicode_data/decompositions_10.rs"),
    include!("unicode_data/decompositions_11.rs"),
    include!("unicode_data/decompositions_12.rs"),
    include!("unicode_data/decompositions_13.rs"),
    include!("unicode_data/decompositions_14.rs"),
];

pub const COMBINING_CLASSES: &[&[(u32, u8)]] = &[
    include!("unicode_data/combining_classes_00.rs"),
    include!("unicode_data/combining_classes_01.rs"),
    include!("unicode_data/combining_classes_02.rs"),
];

pub const COMPOSITIONS: &[&[(u32, u32, u32)]] = &[
    include!("unicode_data/compositions_00.rs"),
    include!("unicode_data/compositions_01.rs"),
    include!("unicode_data/compositions_02.rs"),
];
