#![allow(clippy::wildcard_imports)]
use super::*;
use crate::builtins::builtin_arrays::{
    adjust_array, adjustable_array_p, array_has_fill_pointer_p, fill_pointer, vector_pop,
    vector_push, vector_push_extend,
};

pub(super) const ARRAY_HASH_BUILTINS: &[BuiltinDefinition] = &[
    ("vector", vector as _),
    ("fill-pointer", fill_pointer as _),
    ("vector-push", vector_push as _),
    ("vector-pop", vector_pop as _),
    ("vector-push-extend", vector_push_extend as _),
    ("make-array", make_array as _),
    ("adjust-array", adjust_array as _),
    ("make-sequence", make_sequence as _),
    ("aref", aref as _),
    ("svref", svref as _),
    ("bit", bit as _),
    ("row-major-aref", row_major_aref as _),
    ("array-row-major-index", array_row_major_index as _),
    ("array-in-bounds-p", array_in_bounds_p as _),
    ("array-element-type", array_element_type as _),
    ("adjustable-array-p", adjustable_array_p as _),
    ("array-has-fill-pointer-p", array_has_fill_pointer_p as _),
    ("simple-array-p", simple_array_p as _),
    ("adjustable-array-p", adjustable_array_p as _),
    ("array-displacement", array_displacement as _),
    ("arrayp", arrayp as _),
    ("array-rank", array_rank as _),
    ("array-dimensions", array_dimensions as _),
    ("array-dimension", array_dimension as _),
    ("array-total-size", array_total_size as _),
    ("fill-pointer", fill_pointer as _),
    ("array-has-fill-pointer-p", array_has_fill_pointer_p as _),
    ("vector-push", vector_push as _),
    ("vector-push-extend", vector_push_extend as _),
    ("vector-pop", vector_pop as _),
    ("adjust-array", adjust_array as _),
    ("make-hash-table", make_hash_table as _),
    ("gethash", gethash as _),
    ("remhash", remhash as _),
    ("clrhash", clrhash as _),
    ("hash-table-p", hash_table_p as _),
    ("hash-table-count", hash_table_count as _),
    ("hash-table-test", hash_table_test_value as _),
    ("hash-table-size", hash_table_size_value as _),
    ("hash-table-rehash-size", hash_table_rehash_size_value as _),
    (
        "hash-table-rehash-threshold",
        hash_table_rehash_threshold_value as _,
    ),
    ("hash-table-weakness", hash_table_weakness_value as _),
];
