#![allow(clippy::wildcard_imports)]
use super::*;

pub(super) const CHAR_STRING_BUILTINS: &[BuiltinDefinition] = &[
    ("string", string_value as _),
    ("make-string", make_string as _),
    ("character", character_value as _),
    ("char", character as _),
    ("schar", simple_character as _),
    ("char-code", char_code as _),
    ("char-int", char_int as _),
    ("code-char", code_char as _),
    ("int-char", int_char as _),
    ("char=", character_equal as _),
    ("char/=", character_not_equal as _),
    ("char-equal", character_case_equal as _),
    ("char-not-equal", character_case_not_equal as _),
    ("char<", character_less_than as _),
    ("char>", character_greater_than as _),
    ("char<=", character_less_equal as _),
    ("char>=", character_greater_equal as _),
    ("char-lessp", character_case_less_than as _),
    ("char-greaterp", character_case_greater_than as _),
    ("char-not-lessp", character_case_greater_equal as _),
    ("char-not-greaterp", character_case_less_equal as _),
    ("char-upcase", character_upcase as _),
    ("char-downcase", character_downcase as _),
    ("alpha-char-p", alpha_character_p as _),
    ("alphanumericp", alphanumeric_p as _),
    ("digit-char", digit_character as _),
    ("digit-char-p", digit_character_p as _),
    ("graphic-char-p", graphic_character_p as _),
    ("standard-char-p", standard_character_p as _),
    ("upper-case-p", upper_case_p as _),
    ("lower-case-p", lower_case_p as _),
    ("both-case-p", both_case_p as _),
    ("char-name", character_name as _),
    ("name-char", name_character as _),
    ("string=", string_equal as _),
    ("string-equal", string_case_equal as _),
    ("string<", string_less_than as _),
    ("string>", string_greater_than as _),
    ("string<=", string_less_equal as _),
    ("string>=", string_greater_equal as _),
    ("string-upcase", string_upcase as _),
    ("string-downcase", string_downcase as _),
    ("string-capitalize", string_capitalize as _),
    ("nstring-upcase", nstring_upcase as _),
    ("nstring-downcase", nstring_downcase as _),
    ("nstring-capitalize", nstring_capitalize as _),
    ("string-trim", string_trim as _),
    ("string-left-trim", string_left_trim as _),
    ("string-right-trim", string_right_trim as _),
];
