#![allow(clippy::wildcard_imports)]
use super::*;

pub(super) const IO_BUILTINS: &[BuiltinDefinition] = &[
    ("print", print_value as _),
    ("princ", princ as _),
    ("prin1", prin1 as _),
    ("write", write_value as _),
    ("format", format_value as _),
    ("write-to-string", write_to_string as _),
    ("read-from-string", read_from_string as _),
    ("read", read as _),
    (
        "read-preserving-whitespace",
        read_preserving_whitespace as _,
    ),
    ("make-string-input-stream", make_string_input_stream as _),
    ("make-string-output-stream", make_string_output_stream as _),
    ("open", open_file as _),
    ("probe-file", probe_file as _),
    ("delete-file", delete_file as _),
    ("rename-file", rename_file as _),
    ("file-write-date", file_write_date as _),
    ("truename", truename as _),
    ("get-output-stream-string", get_output_stream_string as _),
    ("read-char", read_char as _),
    ("read-char-no-hang", read_char_no_hang as _),
    ("listen", listen as _),
    ("clear-input", clear_input as _),
    ("read-sequence", read_sequence as _),
    ("peek-char", peek_char as _),
    ("unread-char", unread_char as _),
    ("read-line", read_line as _),
    ("write-char", write_char as _),
    ("write-string", write_string as _),
    ("write-sequence", write_sequence as _),
    ("terpri", terpri as _),
    ("fresh-line", fresh_line as _),
    ("force-output", force_output as _),
    ("finish-output", finish_output as _),
    ("clear-output", clear_output as _),
    ("write-line", write_line as _),
    ("close", close_stream as _),
    ("streamp", streamp as _),
    ("input-stream-p", input_stream_p as _),
    ("output-stream-p", output_stream_p as _),
    ("open-stream-p", open_stream_p as _),
    ("stream-element-type", stream_element_type as _),
    ("stream-external-format", stream_external_format as _),
    ("file-position", file_position as _),
    ("file-length", file_length as _),
    ("random", random as _),
    ("make-random-state", make_random_state as _),
    ("random-state-p", random_state_p as _),
];
