#![allow(clippy::wildcard_imports)]
use super::*;

pub(super) const PREDICATE_BUILTINS: &[BuiltinDefinition] = &[
    ("getf", getf as _),
    ("get-properties", get_properties as _),
    ("null", null as _),
    ("not", null as _),
    ("endp", endp as _),
    ("atom", atom as _),
    ("consp", consp as _),
    ("listp", listp as _),
    ("numberp", numberp as _),
    ("complexp", complexp as _),
    ("integerp", integerp as _),
    ("floatp", floatp as _),
    ("rationalp", rationalp as _),
    ("stringp", stringp as _),
    ("simple-string-p", simple_string_p as _),
    ("characterp", characterp as _),
    ("symbolp", symbolp as _),
    ("packagep", packagep as _),
    ("keywordp", keywordp as _),
    ("symbol-name", symbol_name_value as _),
    ("symbol-package", symbol_package_value as _),
    ("vectorp", vectorp as _),
    ("bit-vector-p", bit_vector_p as _),
    ("simple-bit-vector-p", simple_bit_vector_p as _),
    ("simple-vector-p", simple_vector_p as _),
    ("functionp", functionp as _),
    ("eq", eq as _),
    ("eql", eql as _),
    ("equal", equal as _),
    ("equalp", equalp as _),
    ("identity", identity as _),
    ("complement", complement as _),
    ("constantly", constantly as _),
    ("type-of", type_of as _),
    ("typep", typep as _),
    ("condition-message", condition_message as _),
    ("type-error-datum", type_error_datum as _),
    ("type-error-expected-type", type_error_expected_type as _),
];
