//! The Phase 1 symbols the ownership table assigns to this crate.
//!
//! Generated from `conformance/ownership/symbols.tsv` by the command recorded
//! in `packages/compiler/front/README.md`; regenerate only when that table
//! changes.

/// One kind recorded for an owned symbol.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum SymbolKind {
    /// A CLOS class.
    Class,
    /// A condition type.
    Condition,
    /// A constant variable.
    Constant,
    /// A function.
    Function,
    /// A macro.
    Macro,
    /// A kind with no dedicated registry.
    Other,
    /// A special operator.
    SpecialOperator,
    /// A type specifier name.
    Type,
    /// A special (dynamic) variable.
    Variable,
}

/// One symbol this crate owns.
#[derive(Clone, Copy, Debug)]
pub struct OwnedSymbol {
    /// The owning package name.
    pub package: &'static str,
    /// The symbol name.
    pub name: &'static str,
    /// The kinds recorded for the symbol.
    pub kinds: &'static [SymbolKind],
}

/// Every Phase 1 symbol the ownership table assigns to `ncl-compiler-front`.
#[rustfmt::skip]
pub const OWNED_SYMBOLS: &[OwnedSymbol] = &[
    OwnedSymbol { package: "COMMON-LISP", name: "&ALLOW-OTHER-KEYS", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "&AUX", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "&BODY", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "&ENVIRONMENT", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "&KEY", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "&OPTIONAL", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "&REST", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "&WHOLE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "BLOCK", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "CALL-ARGUMENTS-LIMIT", kinds: &[SymbolKind::Constant] },
    OwnedSymbol { package: "COMMON-LISP", name: "CATCH", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "COMPILATION-SPEED", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "COMPILER-MACRO", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "DEBUG", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "DECLAIM", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "DECLARE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "DECLARATION", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "DEFCLASS", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "DEFGENERIC", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "DEFINE-CONDITION", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "DEFINE-METHOD-COMBINATION", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "DEFMETHOD", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "DEFSTRUCT", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "DEFTYPE", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "DEFUN", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "DISASSEMBLE", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "COMMON-LISP", name: "DYNAMIC-EXTENT", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "EVAL-WHEN", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "FLET", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "FTYPE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "FUNCTION", kinds: &[SymbolKind::SpecialOperator, SymbolKind::Class] },
    OwnedSymbol { package: "COMMON-LISP", name: "FUNCTION-KEYWORDS", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "COMMON-LISP", name: "GO", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "IF", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "IGNORABLE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "IGNORE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "INLINE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "LABELS", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "LAMBDA-LIST-KEYWORDS", kinds: &[SymbolKind::Constant] },
    OwnedSymbol { package: "COMMON-LISP", name: "LAMBDA-PARAMETERS-LIMIT", kinds: &[SymbolKind::Constant] },
    OwnedSymbol { package: "COMMON-LISP", name: "LET", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "LET*", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "LOAD-TIME-VALUE", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "LOCALLY", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "MACROLET", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "MAKE-LOAD-FORM", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "COMMON-LISP", name: "MAKE-LOAD-FORM-SAVING-SLOTS", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "COMMON-LISP", name: "MULTIPLE-VALUE-BIND", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "MULTIPLE-VALUE-CALL", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "MULTIPLE-VALUE-LIST", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "MULTIPLE-VALUE-PROG1", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "MULTIPLE-VALUE-SETQ", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "MULTIPLE-VALUES-LIMIT", kinds: &[SymbolKind::Constant] },
    OwnedSymbol { package: "COMMON-LISP", name: "NOTINLINE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "OPTIMIZE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "OTHERWISE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "PROCLAIM", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "COMMON-LISP", name: "PROGN", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "PROGV", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "PSETQ", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "QUOTE", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "RETURN-FROM", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "ROTATEF", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "SAFETY", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "SATISFIES", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "SETQ", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "SHIFTF", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "COMMON-LISP", name: "SPACE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "SPECIAL", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "SPEED", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "STANDARD", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "SYMBOL-MACROLET", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "TAGBODY", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "THE", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "THROW", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "TYPE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "COMMON-LISP", name: "UNWIND-PROTECT", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "COMMON-LISP", name: "VARIABLE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "*BLOCK-COMPILE-DEFAULT*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*COMPILE-PROGRESS*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*COMPILER-PRINT-VARIABLE-ALIST*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*DEBUG-PRINT-VARIABLE-ALIST*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*DEFAULT-SOURCE-EXTERNAL-FORMAT*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*DISASSEMBLE-ANNOTATE*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*ED-FUNCTIONS*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*EFFICIENCY-NOTE-COST-THRESHOLD*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*EFFICIENCY-NOTE-LIMIT*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*ENCLOSING-SOURCE-CUTOFF*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*FORCIBLY-TERMINATE-THREADS-ON-EXIT*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*INSPECTED*", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "*MODULE-PROVIDER-FUNCTIONS*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*MUFFLED-WARNINGS*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*ON-PACKAGE-VARIANCE*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*STACK-ALLOCATE-DYNAMIC-EXTENT*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*STEPPER-HOOK*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*SUPPRESS-PRINT-ERRORS*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*SYSINIT-PATHNAME-FUNCTION*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*UNDEFINED-WARNING-LIMIT*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "*USERINIT-PATHNAME-FUNCTION*", kinds: &[SymbolKind::Variable] },
    OwnedSymbol { package: "SB-EXT", name: "ALWAYS-BOUND", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "ASSERT-VERSION->=", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "COMPILE-FILE-LINE", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "SB-EXT", name: "COMPILE-FILE-POSITION", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "SB-EXT", name: "CREATE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "DECIMAL-WITH-GROUPED-DIGITS-WIDTH", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "DEFCONSTANT-UNEQL-NAME", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "DEFCONSTANT-UNEQL-NEW-VALUE", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "DEFCONSTANT-UNEQL-OLD-VALUE", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "DEFGLOBAL", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "SB-EXT", name: "DEFINE-LOAD-TIME-GLOBAL", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "SB-EXT", name: "DEFINE-SOURCE-CONTEXT", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "SB-EXT", name: "DEFINED-TYPE-NAME-P", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "DEPRECATED", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "DESCRIBE-COMPILER-POLICY", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "END-BLOCK", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "EVAL-TLF", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "FOLD-IDENTICAL-CODE", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "FREEZE-TYPE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "GET-CAS-EXPANSION", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "GLOBAL", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "IMPLICIT-GENERIC-FUNCTION-NAME", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "MAYBE-INLINE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "NAME-CONFLICT-DATUM", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "NAME-CONFLICT-FUNCTION", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "NAME-CONFLICT-SYMBOLS", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "OVERWRITE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "RENAME", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "RESOLVE-CONFLICT", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "RESTRICT-COMPILER-POLICY", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "SET-MACRO-POLICY", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "SET-SBCL-SOURCE-LOCATION", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "SPIN-LOOP-HINT", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "START-BLOCK", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "STEP-CONDITION-ARGS", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "STEP-CONDITION-FORM", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "STEP-CONDITION-RESULT", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "STEP-CONTINUE", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "STEP-INTO", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "STEP-NEXT", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "STEP-OUT", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "SUPERSEDE", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-EXT", name: "SYMBOL-GLOBAL-VALUE", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "TRULY-THE", kinds: &[SymbolKind::Macro, SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "SB-EXT", name: "TYPEXPAND", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "TYPEXPAND-1", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "TYPEXPAND-ALL", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "UNKNOWN-KEYWORD-ARGUMENT-NAME", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "VALID-TYPE-SPECIFIER-P", kinds: &[SymbolKind::Function] },
    OwnedSymbol { package: "SB-EXT", name: "WITH-CURRENT-SOURCE-FORM", kinds: &[SymbolKind::Macro] },
    OwnedSymbol { package: "SB-SYS", name: "%PRIMITIVE", kinds: &[SymbolKind::SpecialOperator] },
    OwnedSymbol { package: "SB-SYS", name: "MACRO", kinds: &[SymbolKind::Other] },
    OwnedSymbol { package: "SB-SYS", name: "NLX-PROTECT", kinds: &[SymbolKind::SpecialOperator] },
];
