#!/usr/bin/env python3
"""Generate compact Unicode metadata for ncl-lib-strings.

The input files are downloaded from the Unicode Character Database by the
caller.  Keeping generation separate from the Rust crate makes the data
version explicit and keeps the crate free of external dependencies.
"""

from __future__ import annotations

import argparse
from pathlib import Path

UNICODE_VERSION = "16.0.0"
UCD_URL = "https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt"


def read_categories(path: Path) -> list[tuple[int, str]]:
    values: list[tuple[int, str]] = []
    for line in path.read_text(encoding="ascii").splitlines():
        if not line or line.startswith("#"):
            continue
        fields = line.split(";")
        values.append((int(fields[0], 16), fields[2]))
    return values


def compress(values: list[tuple[int, str]]) -> list[tuple[int, int, str]]:
    ranges: list[tuple[int, int, str]] = []
    for codepoint, category in values:
        if ranges and ranges[-1][2] == category and ranges[-1][1] + 1 == codepoint:
            start, _, value = ranges[-1]
            ranges[-1] = (start, codepoint, value)
        else:
            ranges.append((codepoint, codepoint, category))
    return ranges


def generate(source: Path, output: Path) -> None:
    ranges = compress(read_categories(source))
    lines = [
        "// Generated by tools/gen_unicode.py; do not edit.",
        f"// Unicode version: {UNICODE_VERSION}",
        f"// Source: {UCD_URL}",
        "pub const GENERAL_CATEGORY_RANGES: &[(u32, u32, &str)] = &[",
    ]
    lines.extend(f"    (0x{start:X}, 0x{end:X}, \"{category}\")," for start, end, category in ranges)
    lines.append("];\n")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.source, args.output)


if __name__ == "__main__":
    main()
