#!/usr/bin/env python3
"""Generate compact Unicode metadata for ncl-lib-strings.

The input files are downloaded from the Unicode Character Database by the
caller.  Keeping generation separate from the Rust crate makes the data
version explicit and keeps the crate free of external dependencies.
"""

from __future__ import annotations

import argparse
from pathlib import Path

UNICODE_VERSION = "16.0.0"
UCD_URL = "https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt"


def read_categories(path: Path) -> list[tuple[int, str]]:
    values: list[tuple[int, str]] = []
    pending_range: tuple[int, str] | None = None
    for line in path.read_text(encoding="ascii").splitlines():
        if not line or line.startswith("#"):
            continue
        fields = line.split(";")
        codepoint = int(fields[0], 16)
        name = fields[1]
        if name.endswith(", First>"):
            pending_range = (codepoint, fields[2])
            continue
        if name.endswith(", Last>"):
            if pending_range is None:
                raise ValueError(f"range terminator without start: {line}")
            start, category = pending_range
            if category != fields[2] or codepoint < start:
                raise ValueError(f"invalid UnicodeData range: {line}")
            values.extend((value, category) for value in range(start, codepoint + 1))
            pending_range = None
            continue
        if pending_range is not None:
            raise ValueError(f"range start without terminator before: {line}")
        values.append((codepoint, fields[2]))
    if pending_range is not None:
        raise ValueError("unterminated UnicodeData range")
    return values


def read_decompositions(path: Path) -> list[tuple[int, bool, tuple[int, ...]]]:
    values = []
    for line in path.read_text(encoding="ascii").splitlines():
        if not line or line.startswith("#"):
            continue
        fields = line.split(";")
        value = fields[5].split()
        if value:
            compatibility = value[0].startswith("<")
            if compatibility:
                value = value[1:]
            values.append((int(fields[0], 16), compatibility, tuple(int(x, 16) for x in value)))
    return values


def read_combining_classes(path: Path) -> list[tuple[int, int]]:
    values = []
    for line in path.read_text(encoding="ascii").splitlines():
        if not line or line.startswith("#"):
            continue
        fields = line.split(";")
        values.append((int(fields[0], 16), int(fields[3])))
    return values


def compress(values: list[tuple[int, str]]) -> list[tuple[int, int, str]]:
    ranges: list[tuple[int, int, str]] = []
    for codepoint, category in values:
        if ranges and ranges[-1][2] == category and ranges[-1][1] + 1 == codepoint:
            start, _, value = ranges[-1]
            ranges[-1] = (start, codepoint, value)
        else:
            ranges.append((codepoint, codepoint, category))
    return ranges


def generate(source: Path, output: Path) -> None:
    ranges = compress(read_categories(source))
    decompositions = read_decompositions(source)
    combining_classes = [(codepoint, value) for codepoint, value in read_combining_classes(source) if value]
    data_dir = output.parent / "unicode_data"
    data_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by tools/gen_unicode.py; do not edit.",
        f"// Unicode version: {UNICODE_VERSION}",
        f"// Source: {UCD_URL}",
        "pub const GENERAL_CATEGORY_RANGES: &[&[(u32, u32, &str)]] = &[",
    ]
    write_chunks(
        data_dir,
        "general_category_ranges",
        [f"(0x{start:X}, 0x{end:X}, \"{category}\")," for start, end, category in ranges],
        lines,
    )
    lines.append("];\n")
    lines.append("pub const DECOMPOSITIONS: &[&[(u32, bool, &[u32])]] = &[\n")
    write_chunks(
        data_dir,
        "decompositions",
        [
            f"(0x{codepoint:X}, {str(compatibility).lower()}, &[{', '.join(f'0x{value:X}' for value in values)}]),"
            for codepoint, compatibility, values in decompositions
        ],
        lines,
    )
    lines.append("];\n")
    lines.append("pub const COMBINING_CLASSES: &[&[(u32, u8)]] = &[\n")
    write_chunks(
        data_dir,
        "combining_classes",
        [f"(0x{codepoint:X}, {value})," for codepoint, value in combining_classes],
        lines,
    )
    lines.append("];\n")
    lines.append("pub const COMPOSITIONS: &[&[(u32, u32, u32)]] = &[\n")
    write_chunks(
        data_dir,
        "compositions",
        [
            f"(0x{values[0]:X}, 0x{values[1]:X}, 0x{codepoint:X}),"
            for codepoint, compatibility, values in decompositions
            if not compatibility and len(values) == 2
        ],
        lines,
    )
    lines.append("];\n")
    output.write_text("\n".join(lines), encoding="utf-8")


def write_chunks(directory: Path, stem: str, entries: list[str], output: list[str]) -> None:
    for index, start in enumerate(range(0, len(entries), 400)):
        name = f"{stem}_{index:02d}.rs"
        content = "&[\n" + "\n".join(entries[start : start + 400]) + "\n]\n"
        (directory / name).write_text(content, encoding="utf-8")
        output.append(f'    include!("unicode_data/{name}"),')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.source, args.output)


if __name__ == "__main__":
    main()
