use std::cell::RefCell;
use std::cmp::Ordering;
use std::f64::consts::PI;
use std::path::PathBuf;
use std::rc::Rc;

use ncl_syntax::{ReadError, ReadErrorKind, Reader, Span};

use crate::environment::normalize_name;
use crate::evaluator::quoted_form_value;
use crate::package::{self, COMMON_LISP_PACKAGE, KEYWORD_PACKAGE};
use crate::{Environment, Function, Rational, RuntimeError, Stream, Value};

struct DisplacedArray {
    displaced_to: Option<Value>,
    displaced_index_offset: usize,
    storage: Rc<RefCell<Vec<Value>>>,
}

pub fn install(environment: &Environment) {
    for (name, function) in [
        ("+", add as _),
        ("-", subtract as _),
        ("*", multiply as _),
        ("/", divide as _),
        ("sin", sine as _),
        ("cos", cosine as _),
        ("tan", tangent as _),
        ("asin", arc_sine as _),
        ("acos", arc_cosine as _),
        ("atan", arc_tangent as _),
        ("sinh", hyperbolic_sine as _),
        ("cosh", hyperbolic_cosine as _),
        ("tanh", hyperbolic_tangent as _),
        ("asinh", arc_hyperbolic_sine as _),
        ("acosh", arc_hyperbolic_cosine as _),
        ("atanh", arc_hyperbolic_tangent as _),
        ("exp", exponential as _),
        ("log", logarithm as _),
        ("cis", cis as _),
        ("expt", exponentiate as _),
        ("sqrt", square_root as _),
        ("signum", signum as _),
        ("float", float_value as _),
        ("complex", complex as _),
        ("conjugate", conjugate as _),
        ("phase", phase as _),
        ("realpart", realpart as _),
        ("imagpart", imagpart as _),
        ("rational", rational as _),
        ("rationalize", rationalize as _),
        ("=", numeric_equal as _),
        ("<", less_than as _),
        (">", greater_than as _),
        ("<=", less_equal as _),
        (">=", greater_equal as _),
        ("zerop", zerop as _),
        ("plusp", plusp as _),
        ("minusp", minusp as _),
        ("evenp", evenp as _),
        ("oddp", oddp as _),
        ("min", minimum as _),
        ("max", maximum as _),
        ("abs", absolute as _),
        ("1+", increment as _),
        ("1-", decrement as _),
        ("floor", floor as _),
        ("ceiling", ceiling as _),
        ("truncate", truncate as _),
        ("round", round as _),
        ("gcd", greatest_common_divisor as _),
        ("lcm", least_common_multiple as _),
        ("numerator", numerator as _),
        ("denominator", denominator as _),
        ("mod", modulo as _),
        ("rem", remainder as _),
        ("ash", arithmetic_shift as _),
        ("byte", byte as _),
        ("byte-size", byte_size as _),
        ("byte-position", byte_position as _),
        ("ldb", ldb as _),
        ("ldb-test", ldb_test as _),
        ("dpb", dpb as _),
        ("mask-field", mask_field as _),
        ("deposit-field", deposit_field as _),
        ("logbitp", logbitp as _),
        ("logand", logand as _),
        ("logior", logior as _),
        ("logxor", logxor as _),
        ("lognand", lognand as _),
        ("lognor", lognor as _),
        ("logandc1", logandc1 as _),
        ("logandc2", logandc2 as _),
        ("logorc1", logorc1 as _),
        ("logorc2", logorc2 as _),
        ("logeqv", logeqv as _),
        ("boole", boole as _),
        ("lognot", lognot as _),
        ("logtest", logtest as _),
        ("logcount", logcount as _),
        ("integer-length", integer_length as _),
        ("parse-integer", parse_integer as _),
        ("list", list as _),
        ("list*", list_star as _),
        ("make-list", make_list as _),
        ("values-list", values_list as _),
        ("list-length", list_length as _),
        ("nthcdr", nthcdr as _),
        ("acons", acons as _),
        ("pairlis", pairlis as _),
        ("cons", cons as _),
        ("car", car as _),
        ("cdr", cdr as _),
        ("first", first as _),
        ("second", second as _),
        ("third", third as _),
        ("fourth", fourth as _),
        ("fifth", fifth as _),
        ("sixth", sixth as _),
        ("seventh", seventh as _),
        ("eighth", eighth as _),
        ("ninth", ninth as _),
        ("tenth", tenth as _),
        ("rest", rest as _),
        ("append", append as _),
        ("nconc", nconc as _),
        ("revappend", revappend as _),
        ("nreconc", nreconc as _),
        ("length", length as _),
        ("reverse", reverse as _),
        ("nreverse", nreverse as _),
        ("last", last as _),
        ("butlast", butlast as _),
        ("nbutlast", nbutlast as _),
        ("copy-list", copy_list as _),
        ("copy-alist", copy_alist as _),
        ("copy-tree", copy_tree as _),
        ("vector", vector as _),
        ("make-array", make_array as _),
        ("make-sequence", make_sequence as _),
        ("aref", aref as _),
        ("svref", svref as _),
        ("bit", bit as _),
        ("sbit", sbit as _),
        ("row-major-aref", row_major_aref as _),
        ("array-row-major-index", array_row_major_index as _),
        ("array-in-bounds-p", array_in_bounds_p as _),
        ("array-element-type", array_element_type as _),
        ("array-has-fill-pointer-p", array_has_fill_pointer_p as _),
        ("adjustable-array-p", adjustable_array_p as _),
        ("array-displacement", array_displacement as _),
        ("simple-array-p", simple_array_p as _),
        ("arrayp", arrayp as _),
        ("array-rank", array_rank as _),
        ("array-dimensions", array_dimensions as _),
        ("array-dimension", array_dimension as _),
        ("array-total-size", array_total_size as _),
        ("adjust-array", adjust_array as _),
        ("make-hash-table", make_hash_table as _),
        ("gethash", gethash as _),
        ("remhash", remhash as _),
        ("clrhash", clrhash as _),
        ("hash-table-p", hash_table_p as _),
        ("hash-table-count", hash_table_count as _),
        ("hash-table-test", hash_table_test_value as _),
        ("nth", nth as _),
        ("elt", elt as _),
        ("subseq", subseq as _),
        ("fill", fill as _),
        ("replace", replace as _),
        ("copy-seq", copy_seq as _),
        ("concatenate", concatenate as _),
        ("coerce", coerce as _),
        ("string", string_value as _),
        ("make-string", make_string as _),
        ("character", character_value as _),
        ("char", character as _),
        ("schar", simple_character as _),
        ("char-code", char_code as _),
        ("char-int", char_int as _),
        ("code-char", code_char as _),
        ("int-char", int_char as _),
        ("char=", character_equal as _),
        ("char/=", character_not_equal as _),
        ("char-equal", character_case_equal as _),
        ("char-not-equal", character_case_not_equal as _),
        ("char<", character_less_than as _),
        ("char>", character_greater_than as _),
        ("char<=", character_less_equal as _),
        ("char>=", character_greater_equal as _),
        ("char-lessp", character_case_less_than as _),
        ("char-greaterp", character_case_greater_than as _),
        ("char-not-lessp", character_case_greater_equal as _),
        ("char-not-greaterp", character_case_less_equal as _),
        ("char-upcase", character_upcase as _),
        ("char-downcase", character_downcase as _),
        ("alpha-char-p", alpha_character_p as _),
        ("alphanumericp", alphanumeric_p as _),
        ("digit-char", digit_character as _),
        ("digit-char-p", digit_character_p as _),
        ("graphic-char-p", graphic_character_p as _),
        ("standard-char-p", standard_character_p as _),
        ("upper-case-p", upper_case_p as _),
        ("lower-case-p", lower_case_p as _),
        ("both-case-p", both_case_p as _),
        ("char-name", character_name as _),
        ("name-char", name_character as _),
        ("string=", string_equal as _),
        ("string-equal", string_case_equal as _),
        ("string<", string_less_than as _),
        ("string>", string_greater_than as _),
        ("string<=", string_less_equal as _),
        ("string>=", string_greater_equal as _),
        ("string-upcase", string_upcase as _),
        ("string-downcase", string_downcase as _),
        ("string-capitalize", string_capitalize as _),
        ("nstring-upcase", nstring_upcase as _),
        ("nstring-downcase", nstring_downcase as _),
        ("nstring-capitalize", nstring_capitalize as _),
        ("string-trim", string_trim as _),
        ("string-left-trim", string_left_trim as _),
        ("string-right-trim", string_right_trim as _),
        ("getf", getf as _),
        ("get-properties", get_properties as _),
        ("null", null as _),
        ("not", null as _),
        ("endp", endp as _),
        ("atom", atom as _),
        ("consp", consp as _),
        ("listp", listp as _),
        ("numberp", numberp as _),
        ("complexp", complexp as _),
        ("integerp", integerp as _),
        ("floatp", floatp as _),
        ("rationalp", rationalp as _),
        ("stringp", stringp as _),
        ("simple-string-p", simple_string_p as _),
        ("characterp", characterp as _),
        ("symbolp", symbolp as _),
        ("packagep", packagep as _),
        ("keywordp", keywordp as _),
        ("symbol-name", symbol_name_value as _),
        ("symbol-package", symbol_package_value as _),
        ("vectorp", vectorp as _),
        ("fill-pointer", fill_pointer as _),
        ("simple-vector-p", simple_vector_p as _),
        ("functionp", functionp as _),
        ("eq", eq as _),
        ("eql", eql as _),
        ("equal", equal as _),
        ("equalp", equalp as _),
        ("identity", identity as _),
        ("type-of", type_of as _),
        ("typep", typep as _),
        (
            "simple-condition-format-control",
            simple_condition_format_control as _,
        ),
        (
            "simple-condition-format-arguments",
            simple_condition_format_arguments as _,
        ),
        ("__NCL_THE_CHECK", the_check as _),
        ("__NCL_REQUIRE_INTEGER", require_integer as _),
        ("__NCL_REQUIRE_LIST", require_list as _),
        (
            "__NCL_APPEND_OUTPUT_TO_STRING",
            append_output_to_string as _,
        ),
        ("__NCL_ECASE_ERROR", ecase_error as _),
        ("__NCL_ETYPECASE_ERROR", etypecase_error as _),
        ("print", print_value as _),
        ("princ", princ as _),
        ("prin1", prin1 as _),
        ("write", write_value as _),
        ("format", format_value as _),
        ("write-to-string", write_to_string as _),
        ("read-from-string", read_from_string as _),
        ("read", read as _),
        (
            "read-preserving-whitespace",
            read_preserving_whitespace as _,
        ),
        ("make-string-input-stream", make_string_input_stream as _),
        ("%stream-input-position", stream_input_position as _),
        ("make-string-output-stream", make_string_output_stream as _),
        ("open", open_file as _),
        ("probe-file", probe_file as _),
        ("delete-file", delete_file as _),
        ("rename-file", rename_file as _),
        ("file-write-date", file_write_date as _),
        ("truename", truename as _),
        ("get-output-stream-string", get_output_stream_string as _),
        ("read-char", read_char as _),
        ("peek-char", peek_char as _),
        ("unread-char", unread_char as _),
        ("read-line", read_line as _),
        ("write-char", write_char as _),
        ("write-string", write_string as _),
        ("terpri", terpri as _),
        ("fresh-line", fresh_line as _),
        ("write-line", write_line as _),
        ("close", close_stream as _),
        ("streamp", streamp as _),
        ("input-stream-p", input_stream_p as _),
        ("output-stream-p", output_stream_p as _),
    ] {
        let value = Value::builtin(name, function);
        let normalized = normalize_name(name);
        environment.define(normalized.clone(), value.clone());
        environment.define(format!("{COMMON_LISP_PACKAGE}::{normalized}"), value);
    }
    for name in [
        "EVAL",
        "ERROR",
        "SIGNAL",
        "WARN",
        "CERROR",
        "MAKE-CONDITION",
        "COMPILE",
        "LOAD",
        "MAP",
        "REDUCE",
        "MAP-INTO",
        "FIND",
        "POSITION",
        "COUNT",
        "SEARCH",
        "MISMATCH",
        "SORT",
        "STABLE-SORT",
        "MERGE",
        "EVERY",
        "SOME",
        "NOTANY",
        "NOTEVERY",
        "REMOVE",
        "REMOVE-IF",
        "REMOVE-IF-NOT",
        "DELETE",
        "DELETE-IF",
        "DELETE-IF-NOT",
        "REMOVE-DUPLICATES",
        "DELETE-DUPLICATES",
        "SUBSTITUTE",
        "SUBSTITUTE-IF",
        "SUBSTITUTE-IF-NOT",
        "NSUBSTITUTE",
        "NSUBSTITUTE-IF",
        "NSUBSTITUTE-IF-NOT",
        "UNION",
        "NUNION",
        "INTERSECTION",
        "NINTERSECTION",
        "SET-DIFFERENCE",
        "NSET-DIFFERENCE",
        "SET-EXCLUSIVE-OR",
        "NSET-EXCLUSIVE-OR",
        "SUBSETP",
        "SUBTYPEP",
        "UPGRADED-ARRAY-ELEMENT-TYPE",
        "MEMBER",
        "MEMBER-IF",
        "MEMBER-IF-NOT",
        "ADJOIN",
        "ASSOC",
        "ASSOC-IF",
        "ASSOC-IF-NOT",
        "RASSOC",
        "RASSOC-IF",
        "RASSOC-IF-NOT",
        "MAPCAR",
        "MAPC",
        "MAPL",
        "MAPLIST",
        "MAPCAN",
        "MAPCON",
        "MAKE-SYMBOL",
        "GENSYM",
        "MAKE-PACKAGE",
        "INTERN",
        "FIND-SYMBOL",
        "FIND-PACKAGE",
        "DELETE-PACKAGE",
        "RENAME-PACKAGE",
        "PACKAGE-NAME",
        "PACKAGE-USE-LIST",
        "PACKAGE-NICKNAMES",
        "PACKAGE-SHADOWING-SYMBOLS",
        "PACKAGE-USED-BY-LIST",
        "DOCUMENTATION",
        "LIST-ALL-PACKAGES",
        "USE-PACKAGE",
        "UNUSE-PACKAGE",
        "EXPORT",
        "UNEXPORT",
        "IMPORT",
        "UNINTERN",
        "SHADOW",
        "SHADOWING-IMPORT",
        "BOUNDP",
        "CONSTANTP",
        "FBOUNDP",
        "MACRO-FUNCTION",
        "COMPILER-MACRO-FUNCTION",
        "SPECIAL-OPERATOR-P",
        "COMPILED-FUNCTION-P",
        "FUNCTION-LAMBDA-EXPRESSION",
        "FDEFINITION",
        "SYMBOL-FUNCTION",
        "SYMBOL-VALUE",
        "GET",
        "PUTPROP",
        "REMPROP",
        "SYMBOL-PLIST",
        "SET",
        "MAKUNBOUND",
        "FMAKUNBOUND",
        "MAKE-INSTANCE",
        "ALLOCATE-INSTANCE",
        "CHANGE-CLASS",
        "REINITIALIZE-INSTANCE",
        "SHARED-INITIALIZE",
        "ENSURE-GENERIC-FUNCTION",
        "FIND-METHOD",
        "COMPUTE-APPLICABLE-METHODS",
        "GENERIC-FUNCTION-CLASS",
        "GENERIC-FUNCTION-METHODS",
        "GENERIC-FUNCTION-NAME",
        "METHOD-CLASS",
        "METHOD-COMBINATION",
        "METHOD-FUNCTION",
        "METHOD-GENERIC-FUNCTION",
        "METHOD-LAMBDA-LIST",
        "METHOD-QUALIFIERS",
        "METHOD-SPECIALIZERS",
        "SLOT-VALUE",
        "CLASS-OF",
        "FIND-CLASS",
        "CLASS-NAME",
        "SLOT-EXISTS-P",
        "SLOT-BOUNDP",
        "SLOT-MAKUNBOUND",
        "CALL-NEXT-METHOD",
        "NEXT-METHOD-P",
        "COMPUTE-RESTARTS",
        "FIND-RESTART",
        "INVOKE-RESTART",
        "RESTART-NAME",
    ] {
        let value = Value::primitive(name);
        environment.define(name, value.clone());
        environment.define(format!("{COMMON_LISP_PACKAGE}::{name}"), value);
    }
    for (name, value) in [
        ("NIL", Value::Nil),
        ("T", Value::boolean(true)),
        ("ARRAY-RANK-LIMIT", Value::Integer(i64::MAX)),
        ("ARRAY-DIMENSION-LIMIT", Value::Integer(i64::MAX)),
        ("ARRAY-TOTAL-SIZE-LIMIT", Value::Integer(i64::MAX)),
        ("CHAR-CODE-LIMIT", Value::Integer(0x11_00_00)),
        ("MOST-POSITIVE-CHAR-CODE", Value::Integer(0x10_FF_FF)),
        ("BOOLE-CLR", Value::Integer(0)),
        ("BOOLE-SET", Value::Integer(1)),
        ("BOOLE-1", Value::Integer(2)),
        ("BOOLE-2", Value::Integer(3)),
        ("BOOLE-C1", Value::Integer(4)),
        ("BOOLE-C2", Value::Integer(5)),
        ("BOOLE-AND", Value::Integer(6)),
        ("BOOLE-IOR", Value::Integer(7)),
        ("BOOLE-XOR", Value::Integer(8)),
        ("BOOLE-EQV", Value::Integer(9)),
        ("BOOLE-NAND", Value::Integer(10)),
        ("BOOLE-NOR", Value::Integer(11)),
        ("BOOLE-ANDC1", Value::Integer(12)),
        ("BOOLE-ANDC2", Value::Integer(13)),
        ("BOOLE-ORC1", Value::Integer(14)),
        ("BOOLE-ORC2", Value::Integer(15)),
    ] {
        environment.define(name, value.clone());
        environment.define(format!("{COMMON_LISP_PACKAGE}::{name}"), value);
    }
}

include!("numeric.rs");
include!("bitwise.rs");
include!("lists.rs");
include!("characters.rs");
include!("strings.rs");
include!("types.rs");
include!("arrays.rs");
include!("predicates.rs");
include!("streams.rs");
include!("format.rs");
include!("numeric_support.rs");

numeric_builtins!();
bitwise_builtins!();
list_builtins!();
character_builtins!();
string_builtins!();
type_builtins!();
array_builtins!();
predicate_builtins!();
stream_builtins!();
format_builtins!();
numeric_support_builtins!();
